url:
  opendota: https://api.opendota.com/api

spring:
  cloud:
    gcp:
      project-id: jadotaweb
      credentials:
        encoded-key: ${GCP_ENCODED_KEY}

api: 
  base: /api/v1

server:
  port: 8080