url:
  opendota: https://api.opendota.com/api

spring:
  cloud:
    gcp:
      project-id: jadotaweb
      credentials:
        encoded-key: ${GCP_ENCODED_KEY}
  # security:
  #   oauth2:
  #     resourceserver:
  #       jwt:
  #         jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com


api: 
  base: /api/v1