name: Staging

on: 
  push:
    branches:
      - master

env:
  HEROKU_EMAIL: arlwinkarlfajardo@gmail.com

jobs:

  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        working-directory: frontend
        run: npm install

      - name: Build Application
        run: ./build.sh

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "jadotaweb"
          heroku_email: ${{ env.HEROKU_EMAIL }}
          appdir: "backend"
